on:
    push:
        branches:
            - main

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: PipX
              run: python3 -m pip install pipx
            - name: Poetry
              run: pipx install poetry
    test:
        runs-on: ubuntu-latest
        needs: [setup]
        steps:
            - name: Install
              run: poetry install
            - name: Test
              run: pytest .
    publish:
        runs-on: ubuntu-latest
        needs: [setup, test]
        steps:
            - name: Build
              run: poetry build
            - name: Publish
              run: poetry publish -r pypi -u __token__ -p $(PYPI_API_TOKEN)