on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup
              shell: bash
              run: |
                chmod +x ./setup.sh  
                ./setup.sh
            - name: Install
              run: poetry install
            - name: Test
              run: pytest .
    publish:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - uses: actions/checkout@v2
            - name: Setup
              shell: bash
              run: |
                chmod +x ./setup.sh  
                ./setup.sh
            - name: Build
              run: poetry build
            - name: Publish
              run: poetry publish -r pypi -u __token__ -p $(PYPI_API_TOKEN)