on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Install
              run: poetry install
            - name: Test
              run: pytest .
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: poetry build
            - name: Publish
              run: poetry publish -r pypi -u __token__ -p $(PYPI_API_TOKEN)